### ISSUE TITLE
Inbox

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#235]
**Is your feature request related to a problem? Please describe.**

It is a hassle to import / clean data from ISM via the Case Create View

**Describe the solution you'd like**

A place where files can be imported and each case can be automated as far as possible.

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2156

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

Ein paar Eckdaten:

* Der Dublettencheck soll noch ausgebaut werden (#261)
* Es können Test- / Verstorbenen-Listen importiert werden.
* Das Formular "Neuer Indexfall erstellen" ist entfernt. Für manuelle Korrekturen gibt es neu ein ganz einfaches "Neuer Fall" Formular.

**Comment by maennchen** [comment]
@St-Annette Btw. ev. würde es hier Sinn machen das mal kurz in einem Call zu besprechen :)

**Comment by maennchen** [comment]
## Testing

* Mutation Import failt
```
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]  ** (FunctionClauseError) no function clause matching in Hygeia.MutationContext.get_mutation_by_ism_code/1
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (hygeia 0.0.0-noversion) Hygeia.MutationContext.get_mutation_by_ism_code("1174")
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (hygeia 0.0.0-noversion) lib/hygeia/import_context/planner/action/patch_tests.ex:37: Hygeia.ImportContext.Planner.Action.Hygeia.ImportContext.Planner.Action.PatchTests.execute/3
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (hygeia 0.0.0-noversion) lib/hygeia/import_context/planner.ex:82: Hygeia.ImportContext.Planner.execute_action/3
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (elixir 1.11.4) lib/enum.ex:3776: Enumerable.List.reduce/3
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (elixir 1.11.4) lib/enum.ex:2243: Enum.reduce_while/3
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (hygeia 0.0.0-noversion) lib/hygeia/import_context/planner.ex:70: anonymous fn/2 in Hygeia.ImportContext.Planner.execute/2
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:1017: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
[backend-regular-7f654cbfb8-86qdx jshmrtn-simple-site]      (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
```

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

**Comment by jeremyzahner** [comment]
@maennchen Im Falle einer neuen IP Phase auf einem bestehenden Fall mit KP-Phase muss der Endgrund für die KP-Phase korrekt gesetzt werden.
