### ISSUE TITLE
Move Case Tests into separate Tab

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#378]
**Is your feature request related to a problem? Please describe.**

The card `Tests` uses a lot of space in the case base data view. This makes it hard to see all relevant data on the page.

**Describe the solution you'd like**

Remove the tests section in the base data view. Instead add a tab for tests in the case navigation and put a normal CRUD view under that tab.

* List View (Test-Date, Laboratory Date, Test Kind, Test Result, Mutation)
  - Actions: Create / Show / Edit / Delete
* Shoe / Edit view should display case / person header and include all information.

**Describe alternatives you've considered**

none

**Additional context**

none

**References**

https://app.forecast.it/project/P-205/scoping/T2606

**Comment by jeremyzahner** [comment]
Problem:
If there are no Tests for a person, seemingly there is a 500 error.
Somehow, the error reports something wrong with the email configuration.

`[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  14:38:26.311 [error] GenServer #PID<0.13582.0> terminating
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  ** (FunctionClauseError) no function clause matching in Hygeia.TenantContext.tenant_has_outgoing_mail_configuration?/1
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (hygeia 0.0.0-noversion) lib/hygeia/tenant_context.ex:127: Hygeia.TenantContext.tenant_has_outgoing_mail_configuration?(#Ecto.Association.NotLoaded<association :tenant is not loaded>)
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (hygeia_web 0.0.0-noversion) lib/hygeia_web/live/case_live/navigation.sface:182: anonymous fn/6 in HygeiaWeb.CaseLive.Navigation.render/1
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:471: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/4
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (elixir 1.11.4) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:427: Phoenix.LiveView.Diff.traverse/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  Last message: {Phoenix.Channel, %{"params" => %{"_csrf_token" => "JQo9HFBmMwgxSUAsCxRzBnlvKStONyYwwKMY13PC_dpdOeAMK8gt4tUU", "_mounts" => 0, "_track_static" => ["https://staging.covid19-tracing.ch/css/app-5406d626a52103f3c6d227a886330f61.css?vsn=d", "https://staging.covid19-tracing.ch/js/app-f8048ddb3db42f7ea98129561684a390.js?vsn=d"], "browser_features" => %{"date_input" => true, "datetime_local_input" => true}, "timezone" => "Europe/Paris"}, "redirect" => "https://staging.covid19-tracing.ch/cases/d9709214-3c12-48ca-80e1-cc2a3c3faa4e/tests", "session" => "SFMyNTY.g2gDaAJhBXQAAAAIZAACaWRtAAAAFHBoeC1GcDVFNEQtNnVyUGpGVUNoZAAMbGl2ZV9zZXNzaW9uaAJkAAdkZWZhdWx0bggAIFVlhh43nhZkAApwYXJlbnRfcGlkZAADbmlsZAAIcm9vdF9waWRkAANuaWxkAAlyb290X3ZpZXdkACJFbGl4aXIuSHlnZWlhV2ViLkNhc2VMaXZlLkJhc2VEYXRhZAAGcm91dGVyZAAXRWxpeGlyLkh5Z2VpYVdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAiRWxpeGlyLkh5Z2VpYVdlYi5DYXNlTGl2ZS5CYXNlRGF0YW4GAEUxmHh7AWIAAVGA.gAxRQuxCOD6KbK4X9HOJDlTAR6M80FnN0mv6UpJsuqU", "static" => "SFMyNTY.g2gDaAJhBXQAAAADZAAKYXNzaWduX25ld2wAAAABZAALX19zdXJmYWNlX19qZAAFZmxhc2h0AAAAAGQAAmlkbQAAABRwaHgtRnA1RTRELTZ1clBqRlVDaG4GAEUxmHh7AWIAAVGA.ZgnrYXEyr8bIn9cxuWx_b9VMGbXJ3oNGuOHp1614nj0"}, {#PID<0.13509.0>, #Reference<0.283837326.174587905.82581>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: HygeiaWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "44", joined: false, private: %{connect_info: %{peer_data: %{address: {0, 0, 0, 0, 0, 65535, 47439, 60344}, port: 36432, ssl_cert: nil}, session: %{"Elixir.HygeiaWeb.AuthController" => [], "_csrf_token" => "RApEaUcKn-0HDq2K2WN_zCse", "auth" => %Hygeia.UserContext.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, display_name: "SCRUBBED", email: "SCRUBBED", emails: #Ecto.Association.NotLoaded<association :emails is not loaded>, grants: [%Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.285330Z], role: :super_user, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "9a7ec529-e178-4088-884c-09508a7a635a", updated_at: ~U[2021-07-09 18:34:35.285330Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.286184Z], role: :supervisor, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "9a7ec529-e178-4088-884c-09508a7a635a", updated_at: ~U[2021-07-09 18:34:35.286184Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.287086Z], role: :tracer, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "9a7ec529-e178-4088-884c-09508a7a635a", updated_at: ~U[2021-07-09 18:34:35.287086Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.288000Z], role: :super_user, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "d31aa9c7-5221-4199-b7e2-1ca255803e9f", updated_at: ~U[2021-07-09 18:34:35.288000Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.288846Z], role: :supervisor, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "d31aa9c7-5221-4199-b7e2-1ca255803e9f", updated_at: ~U[2021-07-09 18:34:35.288846Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.289665Z], role: :tracer, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "d31aa9c7-5221-4199-b7e2-1ca255803e9f", updated_at: ~U[2021-07-09 18:34:35.289665Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.290561Z], role: :super_user, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "249ca6b1-b95b-4403-b92f-330662baca0a", updated_at: ~U[2021-07-09 18:34:35.290561Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.291444Z], role: :supervisor, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "249ca6b1-b95b-4403-b92f-330662baca0a", updated_at: ~U[2021-07-09 18:34:35.291444Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.292380Z], role: :tracer, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "249ca6b1-b95b-4403-b92f-330662baca0a", updated_at: ~U[2021-07-09 18:34:35.292380Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, %Hygeia.UserContext.Grant{__meta__: #Ecto.Schema.Metadata<:loaded, "user_grants">, inserted_at: ~U[2021-07-09 18:34:35.293236Z], role: :data_exporter, tenant: #Ecto.Association.NotLoaded<association :tenant is not loaded>, tenant_uuid: "662c569b-509f-48d3-84b3-59c74b0843a4", updated_at: ~U[2021-07-09 18:34:35.293236Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}], iam_sub: "85530189185999774", inserted_at: ~U[2020-12-09 08:15:35.399929Z], notifications: #Ecto.Association.NotLoaded<association :notifications is not loaded>, tenants: #Ecto.Association.NotLoaded<association :tenants is not loaded>, updated_at: ~U[2021-07-09 18:34:35.284262Z], uuid: "7d6e0a52-69d4-4776-8f37-5d4db954e418"}, "auth_tokens" => {%{access: %{expires: 43199, hash: :verified, token: "KKWpkgHoeqHVOYHMl94ssdD8neiCB3n0_wI3IibtKs1xc3vCJVa9W75WKm09GfzRCdPp3g"}, id: %{claims: %{:at_hash => "pSBADnc0Y0tVzQdg9EYKbw", :aud => ["87502525980339220@staging", "86761430715523969"], :auth_time => 1629785122, :azp => "87502525980339220@staging", :email => "SCRUBBED", :exp => 1629848929, :gender => "female", :iat =>  (truncated)
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  14:38:26.315 [error] an exception was raised:
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      ** (FunctionClauseError) no function clause matching in Hygeia.TenantContext.tenant_has_outgoing_mail_configuration?/1
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (hygeia 0.0.0-noversion) lib/hygeia/tenant_context.ex:127: Hygeia.TenantContext.tenant_has_outgoing_mail_configuration?(#Ecto.Association.NotLoaded<association :tenant is not loaded>)
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (hygeia_web 0.0.0-noversion) lib/hygeia_web/live/case_live/navigation.sface:182: anonymous fn/6 in HygeiaWeb.CaseLive.Navigation.render/1
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:471: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/4
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (elixir 1.11.4) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:427: Phoenix.LiveView.Diff.traverse/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  14:38:28.242 request_id=0d1d0c00-7a54-42f1-b0c7-ef7112a5c8db [info] GET /cases/d9709214-3c12-48ca-80e1-cc2a3c3faa4e/tests
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  14:38:28.525 request_id=0d1d0c00-7a54-42f1-b0c7-ef7112a5c8db [info] Sent 500 in 283ms
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  14:38:28.526 [error] #PID<0.13591.0> running HygeiaWeb.Endpoint (connection #PID<0.13590.0>, stream id 1) terminated
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  Server: staging.covid19-tracing.ch:80 (http)
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  Request: GET /cases/d9709214-3c12-48ca-80e1-cc2a3c3faa4e/tests
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]  ** (exit) an exception was raised:
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]      ** (FunctionClauseError) no function clause matching in Hygeia.TenantContext.tenant_has_outgoing_mail_configuration?/1
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (hygeia 0.0.0-noversion) lib/hygeia/tenant_context.ex:127: Hygeia.TenantContext.tenant_has_outgoing_mail_configuration?(#Ecto.Association.NotLoaded<association :tenant is not loaded>)
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (hygeia_web 0.0.0-noversion) lib/hygeia_web/live/case_live/navigation.sface:182: anonymous fn/6 in HygeiaWeb.CaseLive.Navigation.render/1
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:370: Phoenix.LiveView.Diff.traverse/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:471: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/4
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (elixir 1.11.4) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:427: Phoenix.LiveView.Diff.traverse/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (phoenix_live_view 0.16.0) lib/phoenix_live_view/diff.ex:444: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
[backend-regular-564685d6bd-zp8fw jshmrtn-simple-site]          (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3`
